// GolBet.Web/Controllers/MatchesController.cs
using GolBet.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GolBet.Web.Controllers;

public class MatchesController : Controller
{
    private readonly IMatchService _matchService;

    public MatchesController(IMatchService matchService)
        => _matchService = matchService;

    // GET /Matches

    // EL GET ES UN ENDPOIMT: APIREST EN .NET 8 SE CONVIERTE UNA ACCION LLAMADA INDEX EN UN ENDPOINT, QUE SE PUEDE ACCEDER DESDE EL NAVEGADOR O DESDE UNA PETICION HTTP. EL ENDPOINT ES /MATCHES, YA QUE EL CONTROLADOR SE LLAMA MATCHESCONTROLLER Y LA ACCION SE LLAMA INDEX. SI SE QUIERE ACCEDER A ESTE ENDPOINT DESDE EL NAVEGADOR, SE PUEDE ESCRIBIR LA URL: https://localhost:5001/Matches (O EL PUERTO QUE ESTÉ UTILIZANDO EL PROYECTO). SI SE QUIERE ACCEDER A ESTE ENDPOINT DESDE UNA PETICION HTTP, SE PUEDE UTILIZAR POSTMAN O CUALQUIER OTRO CLIENTE HTTP PARA HACER UNA PETICION GET A LA URL: https://localhost:5001/Matches.
    public async Task<IActionResult> Index()// INDEX: TODOS LOS CONTROLADORES DE ASP.NET QUE ES EL DASHBOARD DE LOS PARTIDOS, SE LLAMA INDEX POR CONVENCION, YA QUE ES LA ACCION PRINCIPAL DEL CONTROLADOR. SI SE QUIERE ACCEDER A ESTE ENDPOINT DESDE EL NAVEGADOR, SE PUEDE ESCRIBIR LA URL: https://localhost:5001/Matches (O EL PUERTO QUE ESTÉ UTILIZANDO EL PROYECTO). SI SE QUIERE ACCEDER A ESTE ENDPOINT DESDE UNA PETICION HTTP, SE PUEDE UTILIZAR POSTMAN O CUALQUIER OTRO CLIENTE HTTP PARA HACER UNA PETICION GET A LA URL: https://localhost:5001/Matches.
    {
        var board = await _matchService.GetBoardAsync();
        return View(board);
    }
}
